In [1]:
import numpy as np

In [2]:
# 创建一个1维数组
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 创建一个一维数组，利用reshape()函数转换维二维数组
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1 基本属性

#### 01 查看数组是一个几维的数组

In [4]:
x.ndim

1

In [5]:
X.ndim

2

#### 02 shape属性，返回元组

In [6]:
x.shape

(10,)

In [7]:
X.shape

(3, 5)

#### 03 size属性，表示数组中的元素个数

In [8]:
x.size

10

In [9]:
X.size

15

### 2 numpy的数据访问 

#### 如果是一维数组，可以使用和Python一样的访问方式访问数组

In [11]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x[0]

0

In [13]:
x[-1]

9

#### 对于二维或更高维度的数组，不推荐使用`x[0][1]`这样的语法

#### 应该使用`x[传入一个元组]`这样的方式来进行访问

In [15]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[0, 2]

2

#### 切片操作

In [17]:
# 从索引0到索引5但不包含索引5之间的所有元素
x[0:5]

array([0, 1, 2, 3, 4])

In [18]:
# 不写起始参数的话默认为一开始
x[:5]

array([0, 1, 2, 3, 4])

In [19]:
# 不写结束参数的话默认为结尾
x[5:]

array([5, 6, 7, 8, 9])

In [20]:
# 可以有第三个参数表示步长
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 对于二维或更高维度的数组

In [22]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
# 使用这种写法来表示区X数组的前两行，前三列的元素
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

#### 注意，为什么上面不推荐`X[2][3]`这样的语法

In [24]:
X[:2][:3]
# 逐步解析，先取X的前两个元素，再对结果取前三个元素

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### 原因就在于python的解析会导致出现的结果不符合预期

#### 访问方式的组合

In [28]:
# 访问前两行，每行的元素间隔为2
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [29]:
# 行和列都从-1开始
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [30]:
# 取某一行
X[0, :]

array([0, 1, 2, 3, 4])

In [31]:
# 取某一列
X[:, 0]

array([ 0,  5, 10])

#### 注意一个问题，对于ndarray来说，为了效率，取子矩阵返回的是引用，所以对子矩阵的修改会作用于原矩阵

In [33]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [34]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

#### 如果我们想获得一个独立的子矩阵而不是引用怎么办？

In [36]:
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [38]:
subX[0,0] = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [39]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

#### reshape()方法

In [40]:
# 转换为一个1*10的二维矩阵
newX = x.reshape(1, 10)
newX

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [41]:
# 仅仅指定行
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])