## numpy.array中的运算

### 例一 向量的数乘

给定一个向量，让向量中每一个数乘以2

In [1]:
n = 10
L = [i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
# 可见，Python并不支持直接用数乘以列表
2 * L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# 要实现这个逻辑也很简单
A = []
for e in L:
    A.append(2*e)
A

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
# 现在让我们来测试一下它的效率
# 将数据的规模调整到1000000级别

In [5]:
n = 1000000
L = [i for i in range(n)]

In [6]:
# 使用for循环

In [7]:
%%time
A = []
for e in L:
    A.append(2*e)

Wall time: 189 ms


In [8]:
# 使用生成表达式

In [9]:
%%time
A = [2*e for e in L]

Wall time: 104 ms


### 让我们来试一试numpy的效率

In [10]:
import numpy as np
L = np.arange(n)

In [11]:
%%time
A = np.array(2*e for e in L)

Wall time: 14 ms


### 我们可以看到，numpy的速度要远远大于python原生的数组

### 并且，numpy支持向量的数乘

In [12]:
%%time
A = 2*L

Wall time: 2.99 ms


In [13]:
A

array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

### Universal Functions

In [14]:
X = np.arange(1,16).reshape(3, 5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
# 矩阵+1
X+1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [16]:
# 矩阵-1
X-1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
# 乘法
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [18]:
# 浮点数除法
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [19]:
# 整数除法
X // 2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]], dtype=int32)

In [20]:
# 幂运算
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]], dtype=int32)

In [21]:
# 取余数操作
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [22]:
# 取倒数操作
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

#### numpy也内置了很多的数学函数

In [23]:
# 绝对值
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
# 正弦函数
np.sin(X)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [25]:
# 余弦函数
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [26]:
# 正切函数
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [27]:
# 指数函数
np.power(3, X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [28]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]], dtype=int32)

In [29]:
# 对数函数
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

### 例二 矩阵的运算

In [30]:
A = np.arange(4).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [31]:
B = np.full(fill_value=10, shape=(2,2))
B

array([[10, 10],
       [10, 10]])

In [32]:
# 矩阵加法
A + B

array([[10, 11],
       [12, 13]])

In [33]:
# 矩阵减法
A - B

array([[-10,  -9],
       [ -8,  -7]])

注意，如果我们想要求矩阵A和B的乘积，不能使用A*B，因为在numpy中，运算符被定义为对应的数相运算，而不是矩阵乘法的定义

In [34]:
A*B

array([[ 0, 10],
       [20, 30]])

In [35]:
# 如果要求矩阵的乘法，就要使用
# 注意复习矩阵的乘法
A.dot(B)

array([[10, 10],
       [50, 50]])

### 例三 向量和矩阵的运算

In [36]:
# v其实就是一个1行2列的矩阵
v = np.array([1, 2])

In [37]:
A

array([[0, 1],
       [2, 3]])

#### np.tile函数

In [38]:
# 作用是堆叠向量
# 传入两个参数，都是array_like的变量
# 第一个参数表示要堆叠的数组
# 第二个参数分别表示在每个维度上堆叠多少
np.tile(v, (2,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [39]:
v.dot(A)

array([4, 7])

In [40]:
# numpy会自动判断要取行向量还是列向量
# 这里v就被当成了列向量
A.dot(v)

array([2, 8])

### 例四 求矩阵的逆

In [41]:
A

array([[0, 1],
       [2, 3]])

In [42]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [43]:
invA = np.linalg.inv(A)

In [44]:
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [45]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

#### 求伪逆矩阵

In [46]:
X = np.arange(16).reshape(2, 8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [47]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [48]:
X.dot(pinvX)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

#### 逆矩阵和原矩阵相乘是单位矩阵