In [1]:
import numpy as np

### 01 使用索引

In [2]:
# 均值为0，方差为1的正态分布
x = np.random.normal(0, 1, size=1000000)

In [10]:
# 找到最小值
np.min(x)

-5.03548769941351

如果我们想要找到最小值对应在整个数组中的下标，就要使用arg运算

In [7]:
index = np.argmin(x)

In [8]:
x[index]

-5.03548769941351

In [11]:
# 同理，也有np.argmax()
x[np.argmax(x)]

4.988876448076713

In [12]:
np.max(x)

4.988876448076713

### 02 排序和使用索引

In [13]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
# 打乱此数组
np.random.shuffle(x)
x

array([11,  9,  4,  0, 13, 12,  8,  2,  5, 10,  6,  7,  1,  3, 15, 14])

In [15]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
x

array([11,  9,  4,  0, 13, 12,  8,  2,  5, 10,  6,  7,  1,  3, 15, 14])

In [17]:
x.sort()

In [18]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
X = np.random.randint(10, size=(4,4))
X

array([[7, 6, 3, 6],
       [4, 9, 9, 7],
       [5, 7, 1, 1],
       [7, 4, 5, 2]])

In [20]:
# 每一行排好序
np.sort(X)

array([[3, 6, 6, 7],
       [4, 7, 9, 9],
       [1, 1, 5, 7],
       [2, 4, 5, 7]])

In [22]:
# 对每一列排好序
np.sort(X, axis=0)

array([[4, 4, 1, 1],
       [5, 6, 3, 2],
       [7, 7, 5, 6],
       [7, 9, 9, 7]])

### 03 argsort

In [23]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
np.random.shuffle(x)
x

array([12,  6,  9, 14,  4,  2,  0,  7, 13,  3,  5,  1,  8, 15, 11, 10])

In [26]:
# 排序后，第一个数字是索引6，对应原来的数组中是数字0
np.argsort(x)

array([ 6, 11,  5,  9,  4, 10,  1,  7, 12,  2, 15, 14,  0,  8,  3, 13],
      dtype=int64)

#### partition函数

In [27]:
# 以4为分界，比4小的元素放在一边，比4大的元素放在一边
np.partition(x, 4)

array([ 2,  3,  1,  0,  4,  7,  8,  6,  9,  5, 10, 13, 14, 15, 11, 12])

In [28]:
# 同样，也有argpartition
np.argpartition(x, 4)

array([ 5,  9, 11,  6,  4,  7, 12,  1,  2, 10, 15,  8,  3, 13, 14,  0],
      dtype=int64)