### 01 Fancy Indexing

In [1]:
import numpy as np

In [2]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

想要访问索引为3，5，8的元素

In [3]:
ind = [3, 5, 8]

In [4]:
x[ind]

array([3, 5, 8])

也可以是二维索引

In [7]:
# 这里需要使用ndarray数据类型的数组
ind = np.array([[0,2],
       [1,3]])

In [8]:
x[ind]

array([[0, 2],
       [1, 3]])

对于二维数组

In [9]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

想要选取行为 0 1 2，列为 1 2 3 的元素，该怎么做呢？

In [10]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])

In [11]:
X[row, col]

array([ 1,  6, 11])

布尔值索引

In [12]:
col = [True, False, True, True]

In [13]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

### 02 ndarray的比较

In [14]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [15]:
x<3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [16]:
x[x<3]

array([0, 1, 2])

In [17]:
np.sum(x<=3)

4

#### np.count_nonzero()

In [18]:
np.count_nonzero(x <= 3)

4

#### np.any() 只要存在就返回true

In [19]:
np.any(x == 0)

True

In [20]:
np.any(x < 0)

False

#### 只有当对于所有的元素都满足才返回true

In [21]:
np.all(x >= 0)

True

In [22]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
# 查看总共有多少个偶数
np.sum(X % 2 == 0)

8

In [24]:
# 查看每一行共有多少偶数
np.sum(X % 2 == 0, axis=1)

array([2, 2, 2, 2])

In [25]:
# 查看每一列共有多少偶数
np.sum(X%2 ==0, axis=0)

array([4, 0, 4, 0])

In [26]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
# 这里应该使用单个&符号，因为比较运算符是在两个布尔值之间进行比较
# 而这里x>3 和 x<3的值不是布尔值
np.sum((x > 3) & (x < 10))

6

In [28]:
np.sum((x%2 ==0) | (x > 10))

11

In [29]:
np.sum(~(x==0))

15